#include <iostream>

int main() {
    try {
        throw 10;
    } catch (int e) {
        std::cout << "Caught an integer: " << e << std::endl;
    } catch (double e) {
        std::cout << "Caught a double: " << e << std::endl;
    } catch (...) {
        std::cout << "Caught an unknown exception" << std::endl;
    }
    return 0;
}
